#!/usr/bin/env python3
"""Feed the same day-segment palette (palette.py / renderer.resolve_palette)
into i3's window-border colors and the i3bar's colors -- SAME logic as the
wallpaper, kept in sync via the same scrond cron tick (every 15 min).

Does NOT touch the i3status-rs custom block scripts (gwStatus, kanji-date,
carla-status, kanji-explain) -- only i3's own `client.*` directives and the
`bar {}` block.

Mechanism: per an i3 maintainer's own answer to "can I change i3 colors via
i3-msg?" (https://github.com/i3/i3/discussions/6166 -- no, client.* are
config directives, not runtime commands; the recommended pattern is to
`include` another file and rewrite THAT file, then reload) -- this writes
`~/.i3/theme.conf` as a fully self-contained file: literal client.*
directives AND the entire `bar {}` block, no `set $var` indirection at all.
That indirection was tried first and does NOT work reliably: a `set $var`
defined in an included file fails outright when referenced at the top level
of the parent ("Could not parse color"), and silently leaves the literal
unresolved "$varname" string when referenced inside a nested block like
`bar { colors { background $var } }` -- confirmed against a live i3
instance via `i3-msg -t get_bar_config` after both `reload` and a full
`restart`, i3's own `-C` config-check doesn't catch either failure mode.
Putting the complete, literal bar block in the included file sidesteps
this entirely, since nothing is being referenced across files -- it's
handled the exact same way as any other top-level include content.

Drop your own `~/.i3/config`'s `bar {}` block and `client.focused/
focused_inactive/unfocused/background` lines entirely, in favor of
`include ~/.i3/theme.conf` -- so, unlike the earlier marker-rewrite
approach, this file NEVER touches your main i3 config, no drift/--force
friction (handy if `~/.i3/config` is itself managed by a dotfiles tool).
If you run i3 on multiple machines with different bar setups, just make
the `include` line conditional per-host in your own config.

client.urgent / bar.urgent_workspace stay in config.tmpl itself (static,
vivid, deliberately not themed) -- an urgent window/workspace needs to
stay an unambiguous "pay attention" signal regardless of mood palette.
"""
import sys
from datetime import date, datetime
from pathlib import Path

from config import DEFAULT_CONFIG_PATH, load_config
from renderer import resolve_palette

THEME_CONF_PATH = Path.home() / ".i3" / "theme.conf"

# Static bar settings duplicated from your own i3 config -- not themed,
# just needs to be part of this self-contained included block.
_BAR_FONT = "pango:DejaVu Sans Mono, RocknRoll One, FontAwesome 12"
_BAR_STATUS_COMMAND = "i3status-rs ~/.i3/status_config.toml"


def build_theme_conf(cfg) -> str:
    palette, _, _, _ = resolve_palette(date.today(), datetime.now(), cfg)
    p = palette

    return "\n".join([
        "# Generated by jikan/i3_theme.py -- do not edit by hand, regenerated",
        "# every 15 min from the current day-segment palette.",
        "# client.urgent/urgent_workspace stay static in your main i3 config --",
        "# see this script's module docstring for why (and why this is a fully",
        "# self-contained include, not `set $var` + reference from the parent).",
        "",
        f"client.focused          {p.accent} {p.background} {p.primary} {p.accent} {p.accent}",
        f"client.focused_inactive {p.secondary} {p.background} {p.secondary} {p.tertiary}",
        f"client.unfocused        {p.tertiary} {p.background} {p.tertiary} {p.tertiary}",
        f"client.background       {p.background}",
        "",
        "bar {",
        f"    font {_BAR_FONT}",
        "    position bottom",
        f"    status_command {_BAR_STATUS_COMMAND}",
        "    strip_workspace_numbers yes",
        "    colors {",
        "        separator #666666",
        f"        background {p.background}",
        f"        statusline {p.primary}",
        f"        focused_workspace {p.accent} {p.accent} {p.background}",
        f"        active_workspace {p.secondary} {p.secondary} {p.primary}",
        f"        inactive_workspace {p.background} {p.background} {p.tertiary}",
        "        urgent_workspace #2f343a #900000 #ffffff",
        "    }",
        "}",
        "",
    ])


def main() -> int:
    import subprocess

    cfg = load_config(DEFAULT_CONFIG_PATH)
    THEME_CONF_PATH.parent.mkdir(parents=True, exist_ok=True)
    THEME_CONF_PATH.write_text(build_theme_conf(cfg), encoding="utf-8")
    print(f"wrote {THEME_CONF_PATH}")

    subprocess.run(["i3-msg", "reload"], check=True, capture_output=True)
    print("i3 reloaded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
